apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-terracotta.fullname" . }}-trg-service
  namespace: {{ template "kube-terracotta.namespace" . }}
  labels:
    app: "trg"
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- include "kube-terracotta.labels" . | nindent 4 }}
    {{- with .Values.extraLabels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: trg-port
      port: 8080
  selector:
    app: "trg"
