apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "kube-terracotta.fullname" . }}-trg
  namespace: {{ template "kube-terracotta.namespace" . }}
  labels:
    app: "trg"
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- include "kube-terracotta.labels" . | nindent 4 }}
    {{- with .Values.extraLabels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "trg"
  serviceName: {{ template "kube-terracotta.fullname" . }}-trg-service
  template:
    metadata:
      labels:
        app: "trg"
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      serviceAccountName: {{ template "kube-terracotta.fullname" . }}-sa
      {{- with .Values.trg.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.trg.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.terracotta.security.isConfigured }}
      initContainers:
        - name: "trg-server-init"
          image: busybox:latest
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/bin/sh", "-c", "tar -xzf /certs/trg/security.tar.gz --directory /opt/terracotta/config"]
          volumeMounts:
            - name: trg-security-volume
              mountPath: /certs/trg
            - name: emptydir
              mountPath: /opt/terracotta/config
      {{- end }}
      containers:
        - name: "trg-server"
          image: "{{ $.Values.trg.trgImage }}:{{ $.Values.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: TRG_CONNECTION_URL
              value: "terracotta://{{ template "serverUrl" . }}"
            - name: TRG_CONFIG_FILE
              value: "/opt/terracotta/config/rest-gateway.properties"
            - name: TRG_CONNECTION_TIMEOUT
              value: {{ .Values.trg.connectionTimeout | quote }}
            - name: "JSON_LOGGING"
              value: {{ .Values.trg.jsonLogging | quote }}
            - name: "JSON_LOGGING_AUDIT"
              value: {{ .Values.trg.jsonAuditLogging | quote }}
            - name: "JSON_LOGGING_SECURITY"
              value: {{ .Values.trg.jsonSecurityLogging | quote }}
            {{- range $key, $val := .Values.extraEnvs }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end }}
            {{- range $key, $val := .Values.tms.extraEnvs }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end }}
          ports:
            - name: trg-port
              containerPort: 8080
          volumeMounts:
            - name: trgdata
              mountPath: /opt/terracotta/run
          {{- if .Values.terracotta.security.isConfigured }}
            - name: emptydir
              mountPath: /opt/terracotta/config
          {{- end }}
          {{- if .Values.trg.resources }}
          resources:
{{ toYaml .Values.trg.resources | indent 12 }}
          {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.terracotta.security.isConfigured }}
      volumes:
        - name: trg-security-volume
          configMap:
            name: {{ template "kube-terracotta.fullname" . }}-trg-security-configmap
        - name: emptydir
          emptyDir:
  {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: trgdata
      spec:
        volumeMode: "Filesystem"
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.storageClass }}
        storageClassName: {{ .Values.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.trg.storage }}
