---
# /*
#  * Copyright (c) 2024 IBM Corporation
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
data:
  config-sources.yml: |
    sources:
    - type: YAML
      allowEdit: false
      properties:
        location: apigw-config.yml
    {{- if .Values.apigw.extraConfigSources }}
    {{- toYaml .Values.apigw.extraConfigSources | nindent 4 -}}
    {{- end }}
  apigw-config.yml: |
    apigw:
      {{- range $key, $value := .Values.apigw.configSources }}
        {{- if kindIs "map" $value }}
          {{- printf "%s:" $key | nindent 6 }}
          {{- include "common.utils.renderNestedMap" (dict "map" $value "ctx" $ "depth" 8) }}
        {{- else if kindIs "string" $value }}
          {{- printf "%s: %s" $key (tpl $value $) }}
        {{- else if or (kindIs "bool" $value) (or (kindIs "float" $value) (kindIs "int" $value)) }}
          {{- printf "%s: %v" $key $value }}
        {{- end }}
      {{- end }}
  {{ if .Values.apigw.applicationProperties -}}
  application.properties: |
    {{- printf "%s" (tpl .Values.apigw.applicationProperties .) | nindent 4 }}
  {{ else -}}
  application.properties: |
    user.Administrator.password=$env{ADMINISTRATOR_PASSWORD}
  {{- end}}