---
# /*
#  * Copyright (c) 2021 Software AG, Darmstadt, Germany and/or its licensors
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
data:
  config-sources.yml: |
    sources:
    - type: YAML
      allowEdit: false
      properties:
        location: apigw-config.yml

  apigw-config.yml: |
    apigw: 
      {{- range $key, $value := .Values.apigw.configSources }}
      {{- if kindIs "map" $value }}
      {{ $key }}:

      {{- range $key1, $value1 := $value }}
        {{- if kindIs "map" $value1 }}
        {{ $key1 }}:

        {{- range $key2, $value2 := $value1 }}
          {{- if kindIs "map" $value2 }}
          {{ $key2 }}:

          {{- range $key3, $value3 := $value2 }}
            {{- if kindIs "string" $value3 }}
            {{ $key3 }}: {{ (tpl $value3 $) }}
            {{- end }}
          {{- end }}

          {{- else if kindIs "string" $value2 }}
          {{ $key2 }}: {{ (tpl $value2 $) }}
          {{- end }}
        {{- end }}

        {{- else if kindIs "string" $value1 }}
        {{ $key1 }}: {{ (tpl $value1 $) }}
        {{- end }}
        {{- end }}
        {{- else if kindIs "string"}}
          {{  $key }}: {{ (tpl $value $) }}
        {{- end }}
      {{- end }}
    
  {{ if .Values.apigw.applicationProperties -}}
  application.properties: |
    {{- printf "%s" (tpl .Values.apigw.applicationProperties .) | nindent 4 }}
  {{ else -}}
  application.properties: |
    user.Administrator.password=$env{ADMINISTRATOR_PASSWORD}
  {{- end}}