{{- if .Values.podDisruptionBudget.enabled }}
{{- required "A valid PodDisruptionBudgetSpec is required!" .Values.podDisruptionBudget.spec -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
spec:
  {{- toYaml .Values.podDisruptionBudget.spec | nindent 2 }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 8 }}
      {{- with .Values.extraLabels -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apigw.extraLabels -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
