{{- if .Values.podDisruptionBudget.enabled }}
{{- required "A valid PodDisruptionBudgetSpec is required!" .Values.podDisruptionBudget.spec -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
spec:
  {{- toYaml .Values.podDisruptionBudget.spec | nindent 2 }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 8 }}
      {{- toYaml .Values.extraLabels | nindent 8 }}
      {{- toYaml .Values.apigw.extraLabels | nindent 8 }}
{{- end }}
