{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 8 }}
      {{- with .Values.extraLabels -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apigw.extraLabels -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
