apiVersion: policy/v1
kind: PodDisruptionBudget
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 8 }}
      {{- with .Values.extraLabels -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apigw.extraLabels -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
