{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
spec:
  {{- with podDisruptionBudget.spec -}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 8 }}
      {{- with .Values.extraLabels -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apigw.extraLabels -}}
      {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
