{{- if .Values.secrets.generateSecrets }}
---
# /*
#  * Copyright (c) 2026 IBM Corporation
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  */

{{- if eq (include "apianalyticstore.deployElasticsearch" .) "true" }}
# Elasticsearch IBM User Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apianalyticstore.elasticsecret" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  roles: |
    superuser
  username: {{ default "ibm" .Values.elasticsearch.secretUserKey }}
  password: {{ randAlphaNum 16 }}
{{- end }}

{{- if eq (include "apianalyticstore.deployOpensearch" .) "true" }}
---
# OpenSearch Admin Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apianalyticstore.opensearchadminsecret" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  username: admin
  password: {{ randAlphaNum 16 }}
---
# OpenSearch IBM User Secret (security config)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apianalyticstore.opensearchsecret" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  securityconfig.yml: |
    ---
    _meta:
      type: "config"
      config_version: 2
{{- end }}

{{- if eq (include "apianalyticstore.deployOpensearchDashboards" .) "true" }}
---
# OpenSearch Dashboards User Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apianalyticstore.opensearchdashboardssecret" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  username: {{ default "kibanaserver" .Values.opensearchDashboards.secretName }}
  password: {{ randAlphaNum 16 }}
{{- end }}

{{- end }}

