apiVersion: v1
entries:
  apigateway:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-03T11:24:34.471528808+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    - name: prometheus-elasticsearch-exporter
      repository: https://prometheus-community.github.io/helm-charts
      tags:
      - prometheus-elasticsearch-exporter
      version: 5.0.0
    description: API Gateway Helm Chart for Kubernetes
    digest: fd3273458fe51092cb7205e435c5719c59bf0d500e168dcf0552d6af2544c83a
    name: apigateway
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/apigateway-1.0.0.tgz
    version: 1.0.0
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.0.0
    created: "2023-11-03T11:24:34.471962633+01:00"
    description: A Library Helm Chart for grouping common logic between Software AG
      charts. This chart is not deployable by itself.
    digest: adbacb9a032d1432cca195b239b74af2471be6b3bd6be98ee9c883edd474bbd4
    home: https://softwareag.com
    icon: https://softwareag.com/downloads/logos/softwareag-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - softwareag
    maintainers:
    - name: SoftwareAG
      url: https://softwareag.com
    name: common
    sources:
    - https://github.com/softwareag/webmethods-helm-charts
    type: library
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/common-1.0.0.tgz
    version: 1.0.0
  developerportal:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-03T11:24:34.475832747+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    - name: prometheus-elasticsearch-exporter
      repository: https://prometheus-community.github.io/helm-charts
      tags:
      - prometheus-elasticsearch-exporter
      version: 5.0.0
    description: webMethods Developer Portal Helm Chart for Kubernetes
    digest: a5f7e07680f57f8254d76d3722ced7638508b4e4f522dbcfc7c3d2b689ae9a42
    name: developerportal
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/developerportal-1.0.0.tgz
    version: 1.0.0
  microservicesruntime:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-03T11:24:34.477623066+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: Microservices Runtime (MSR) Helm Chart for Kubernetes
    digest: 412c5917109aed3d23ed1122eac8f4fd18478cf764f56c0e3db09164a0ba6e85
    name: microservicesruntime
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/microservicesruntime-1.0.0.tgz
    version: 1.0.0
  mywebmethodsserver:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-03T11:24:34.478857482+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: My webMethods Server (MWS) Helm Chart for Kubernetes
    digest: de6146caafb6b589068a5c319b7e69abe4cfd97fbb84c1e98d4130e3909df5a7
    name: mywebmethodsserver
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/mywebmethodsserver-1.0.0.tgz
    version: 1.0.0
  universalmessaging:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-03T11:24:34.480037208+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: Universal Messaging (UM) Helm Chart for Kubernetes
    digest: f6521bd35456de522dbc7cecd6d47432ce52e34572a0fbd3228f16d1823e768a
    name: universalmessaging
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/universalmessaging-1.0.0.tgz
    version: 1.0.0
generated: "2023-11-03T11:24:34.468383861+01:00"
