apiVersion: v1
entries:
  apigateway:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-12-05T18:38:50.040267815+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    - condition: prometheus-elasticsearch-exporter.enabled
      name: prometheus-elasticsearch-exporter
      repository: https://prometheus-community.github.io/helm-charts
      tags:
      - prometheus-elasticsearch-exporter
      version: 5.0.0
    description: API Gateway Helm Chart for Kubernetes
    digest: 58a47e049cf4797650261c4cc0dc754dd9174c303df222482fca4f60c9f79930
    name: apigateway
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/apigateway-1.0.0.tgz
    version: 1.0.0
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.0.0
    created: "2023-12-05T18:38:50.041131535+01:00"
    description: A Library Helm Chart for grouping common logic between Software AG
      charts. This chart is not deployable by itself.
    digest: a621bb9b71c1c4e10cacb8c8f75ff9a48ae165ee94c42ba33c3dfa5c9bd202d9
    home: https://softwareag.com
    icon: https://softwareag.com/downloads/logos/softwareag-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - softwareag
    maintainers:
    - name: SoftwareAG
      url: https://softwareag.com
    name: common
    sources:
    - https://github.com/softwareag/webmethods-helm-charts
    type: library
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/common-1.0.1.tgz
    version: 1.0.1
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.0.0
    created: "2023-12-05T18:38:50.040717161+01:00"
    description: A Library Helm Chart for grouping common logic between Software AG
      charts. This chart is not deployable by itself.
    digest: 4c9eda6a44b05e9aa23e33196a67dd1ac6fd767d6a14cee40a312a320a780c8d
    home: https://softwareag.com
    icon: https://softwareag.com/downloads/logos/softwareag-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - softwareag
    maintainers:
    - name: SoftwareAG
      url: https://softwareag.com
    name: common
    sources:
    - https://github.com/softwareag/webmethods-helm-charts
    type: library
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/common-1.0.0.tgz
    version: 1.0.0
  developerportal:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-12-05T18:38:50.044503176+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    - name: prometheus-elasticsearch-exporter
      repository: https://prometheus-community.github.io/helm-charts
      tags:
      - prometheus-elasticsearch-exporter
      version: 5.0.0
    description: webMethods Developer Portal Helm Chart for Kubernetes
    digest: bc769fda5350318c147a5120ac23e65ac6a2f882e9c4d0d66effa4a54497795b
    name: developerportal
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/developerportal-1.0.0.tgz
    version: 1.0.0
  microservicesruntime:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-12-05T18:38:50.047744842+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: Microservices Runtime (MSR) Helm Chart for Kubernetes
    digest: 1ba43f06b76fd14a3a5bb29c006b5b44d9384a718defe4a123112a4f9717dbc4
    name: microservicesruntime
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/microservicesruntime-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-12-05T18:38:50.046063675+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: Microservices Runtime (MSR) Helm Chart for Kubernetes
    digest: 0a05b4151aad3e5207e9cdfa27ae686b1211ca83d0542451bfdec7e0454536ff
    name: microservicesruntime
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/microservicesruntime-1.0.0.tgz
    version: 1.0.0
  mywebmethodsserver:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-12-05T18:38:50.049030275+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: My webMethods Server (MWS) Helm Chart for Kubernetes
    digest: eb3dd91b5fd14edb1496256d9ef9973c36cef9f9ca4ea8c313089e6d4baf1675
    name: mywebmethodsserver
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/mywebmethodsserver-1.0.0.tgz
    version: 1.0.0
  universalmessaging:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-12-05T18:38:50.050316565+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: Universal Messaging (UM) Helm Chart for Kubernetes
    digest: 7916bb18051eb75afb80e1bea33eca9ea1bae5c11f09f375375b04c81dc284df
    name: universalmessaging
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/universalmessaging-1.0.0.tgz
    version: 1.0.0
generated: "2023-12-05T18:38:50.036678046+01:00"
