apiVersion: v1
entries:
  apigateway:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-21T17:45:25.447963756+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    - name: prometheus-elasticsearch-exporter
      repository: https://prometheus-community.github.io/helm-charts
      tags:
      - prometheus-elasticsearch-exporter
      version: 5.0.0
    description: API Gateway Helm Chart for Kubernetes
    digest: bf53b1f39bf27418518507ab8058ccba11dd0b6f3628da22f7d8fefb360c218d
    name: apigateway
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/apigateway-1.0.0.tgz
    version: 1.0.0
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.0.0
    created: "2023-11-21T17:45:25.448744421+01:00"
    description: A Library Helm Chart for grouping common logic between Software AG
      charts. This chart is not deployable by itself.
    digest: b843181ab5f3da38276c921296e38c41cfdc4f1bcde44eb0a9520f206fc0b7eb
    home: https://softwareag.com
    icon: https://softwareag.com/downloads/logos/softwareag-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - softwareag
    maintainers:
    - name: SoftwareAG
      url: https://softwareag.com
    name: common
    sources:
    - https://github.com/softwareag/webmethods-helm-charts
    type: library
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/common-1.0.1.tgz
    version: 1.0.1
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.0.0
    created: "2023-11-21T17:45:25.448376657+01:00"
    description: A Library Helm Chart for grouping common logic between Software AG
      charts. This chart is not deployable by itself.
    digest: 4c9eda6a44b05e9aa23e33196a67dd1ac6fd767d6a14cee40a312a320a780c8d
    home: https://softwareag.com
    icon: https://softwareag.com/downloads/logos/softwareag-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - softwareag
    maintainers:
    - name: SoftwareAG
      url: https://softwareag.com
    name: common
    sources:
    - https://github.com/softwareag/webmethods-helm-charts
    type: library
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/common-1.0.0.tgz
    version: 1.0.0
  developerportal:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-21T17:45:25.451034423+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    - name: prometheus-elasticsearch-exporter
      repository: https://prometheus-community.github.io/helm-charts
      tags:
      - prometheus-elasticsearch-exporter
      version: 5.0.0
    description: webMethods Developer Portal Helm Chart for Kubernetes
    digest: c9f2a3e1464aaf37b5d9b8e2d25344bdcab7241a482efb6217f9c15cc4df7e2c
    name: developerportal
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/developerportal-1.0.0.tgz
    version: 1.0.0
  microservicesruntime:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-21T17:45:25.452776461+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: Microservices Runtime (MSR) Helm Chart for Kubernetes
    digest: 260e47f7c50a06036bef3f695a451da30b528e34e1214cb5ff417ba56cc4dfa4
    name: microservicesruntime
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/microservicesruntime-1.0.0.tgz
    version: 1.0.0
  mywebmethodsserver:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-21T17:45:25.455108265+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: My webMethods Server (MWS) Helm Chart for Kubernetes
    digest: b786ab8a202d6830182e4c4baf45d1bad143bf72b581f6d494cbcfafa67700d6
    name: mywebmethodsserver
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/mywebmethodsserver-1.0.0.tgz
    version: 1.0.0
  universalmessaging:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2023-11-21T17:45:25.45686697+01:00"
    dependencies:
    - name: common
      repository: https://open-source.softwareag.com/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.x.x
    description: Universal Messaging (UM) Helm Chart for Kubernetes
    digest: 07a6dc71dda45d68de0fac40c5b56f1472d73e99590352491193b51ad5297f63
    name: universalmessaging
    type: application
    urls:
    - https://open-source.softwareag.com/webmethods-helm-charts/charts/universalmessaging-1.0.0.tgz
    version: 1.0.0
generated: "2023-11-21T17:45:25.444162612+01:00"
