name: Test all Charts with 'dry-run' option

on:
  push:
    branches-ignore:
      - main              # Run on all not 'main' branches

jobs:
  release:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          rm -Rf *

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          sh ./get_helm.sh
          rm ./get_helm.sh

      - name: Dry-run of apigateway
        run: |
          helm dependencies update apigateway/helm
          helm template apigw      apigateway/helm

      - name: Dry-run of developerportal
        run: |
          helm dependencies update developerportal/helm
          helm template devportal  developerportal/helm

      - name: Dry-run of microservicesruntime
        run: |
          helm dependencies update microservicesruntime/helm
          helm template msr        microservicesruntime/helm

      - name: Dry-run of mywebmethodsserver
        run: |
          helm dependencies update mywebmethodsserver/helm
          helm template mws        mywebmethodsserver/helm

      - name: Dry-run of universalmessaging
        run: |
          helm dependencies update universalmessaging/helm
          helm template um         universalmessaging/helm

      - name: Dry-run of terracottabigmemorymax
        run: |
          helm dependencies update terracottabigmemorymax/helm
          helm template tc         terracottabigmemorymax/helm
