name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          rm -Rf *

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Helm README Documentation with jnorwood
        run: |
          sudo docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:latest

      - name: Remove README.md template files
        run: |
          find . -name "README.md.gotmpl" | xargs rm

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          sh ./get_helm.sh
          rm ./get_helm.sh

      - name: Update dependencies and package helm charts
        run: |
          helm package --dependency-update common/helm
          helm package --dependency-update apigateway/helm
          helm package --dependency-update developerportal/helm
          helm package --dependency-update microservicesruntime/helm
          helm package --dependency-update mywebmethodsserver/helm
          helm package --dependency-update universalmessaging/helm
          helm package --dependency-update terracottabigmemorymax/helm

      - name: Push Helm Charts to this GitHub repo branch 'gh-pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          ls -la
          git config --global user.name  "${{ github.event.head_commit.committer.name  }}"
          git config --global user.email "${{ github.event.head_commit.committer.email }}"
          git clone --depth 1 https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} -b gh-pages
          cp    *.md                          webmethods-helm-charts/
          mkdir -p                            webmethods-helm-charts/charts
          cp    *.tgz                         webmethods-helm-charts/charts
          cd                                  webmethods-helm-charts/charts
          helm repo index . --url https://ibm.github.io/webmethods-helm-charts/charts
          git add .
          git commit -am "${{ github.event.head_commit.message }}"
          git branch -M      gh-pages
          git push -f origin gh-pages
